export const API_URL = "https://api.themoviedb.org/3";

export const API_KEY_3 = "23506cba8a6228cba81e4c4c021d4ecd";

export const API_KEY_4 =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZjRjYTRmM2E5NzUwZGE1MzQ1MDY0NmNlZDMxMjM5NyIsInN1YiI6IjVhYzlmNWRkOTI1MTQxNjJhZTA1Njk0NiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Fc4f9DVB6pFWh6hIjYe0NCC4pImdmNzDIfi_3Nb3tC4";

export const moviesDB = [
  {
    "popularity": 711.949,
    "vote_count": 719,
    "video": false,
    "poster_path": "/cCm0H9R61kKtN2f4OJ7uES4nmp4.jpg",
    "id": 338762,
    "adult": false,
    "backdrop_path": "/lP5eKh8WOcPysfELrUpGhHJGZEH.jpg",
    "original_language": "en",
    "original_title": "Bloodshot",
    "genre_ids": [28, 878],
    "title": "Бладшот",
    "vote_average": 7.3,
    "overview": "Главный герой — Анджело Морталли, современный Франкенштейн на службе у правительства — был реанимирован, соответственно, из мертвых и превращен в «машину убийства». Для этого ФБР стерло его память и запустило в кровь специальные микрокопьютеры, которые помогают телу Анджело быстро заживлять раны и контролировать различные электронные устройства… Завязка истории происходит, когда эта прокаченная машина убийства, выходит из-под контроля и объявляет войну своим прежним работодателям, лишившем его памяти.",
    "release_date": "2020-02-20"
  }, {
    "popularity": 513.375,
    "vote_count": 2695,
    "video": false,
    "poster_path": "/dcbPgUymJt6tbUbs7U6L2Jc0wXD.jpg",
    "id": 419704,
    "adult": false,
    "backdrop_path": "/5BwqwxMEjeFtdknRV792Svo0K1v.jpg",
    "original_language": "en",
    "original_title": "Ad Astra",
    "genre_ids": [12, 18, 9648, 878, 53],
    "title": "К звёздам",
    "vote_average": 5.9,
    "overview": "Инженер армейского корпуса путешествует по Галактике в поисках отца, который отправился на поиски внеземной цивилизации 20 лет назад и исчез.",
    "release_date": "2019-09-17"
  }, {
    "popularity": 344.397,
    "vote_count": 812,
    "video": false,
    "poster_path": "/dMfPWvQkETaB19fVQ50MQYeHCdQ.jpg",
    "id": 570670,
    "adult": false,
    "backdrop_path": "/uZMZyvarQuXLRqf3xdpdMqzdtjb.jpg",
    "original_language": "en",
    "original_title": "The Invisible Man",
    "genre_ids": [27, 878, 53],
    "title": "Человек-невидимка",
    "vote_average": 7,
    "overview": "Когда отношения с богатым и гениальным учёным оборачиваются сплошным насилием и агрессией, Сесилия Касс сбегает под покровом ночи. Скрываться ей помогают сестра, друг детства и его дочь-подросток. Вскоре бывший бойфренд Сесилии совершает самоубийство и оставляет ей в наследство немалую долю своего огромного состояния. Однако девушка подозревает, что её бывший инсценировал свою смерть и на самом деле всё ещё жив. Столкнувшись с чередой жутких и смертельно опасных происшествий, Сесилия постепенно начинает сходить с ума, отчаянно пытаясь доказать, что её преследует некто невидимый.",
    "release_date": "2020-02-26"
  }, {
    "popularity": 313.778,
    "vote_count": 7870,
    "video": false,
    "poster_path": "/dYgC6hEJvrIZ9fojVV2Lbg3PQr1.jpg",
    "id": 363088,
    "adult": false,
    "backdrop_path": "/6P3c80EOm7BodndGBUAJHHsHKrp.jpg",
    "original_language": "en",
    "original_title": "Ant-Man and the Wasp",
    "genre_ids": [28, 12, 35, 878],
    "title": "Человек-муравей и Оса",
    "vote_average": 7,
    "overview": "Скотт Лэнг, известный также, как Человек-Муравей уже заслужил право оказаться в команде Мстителей, но желание быть ближе к собственной дочке удерживает его в родном Сан-Франциско — до тех пор, пока доктор Хэнк Пим, создавший когда-то изменяющий размеры своего владельца чудо-костюм, не призывает Скотта присоединиться к новой, опасной миссии. А помогать в противостоянии с коварным врагом Человеку-Муравью будет новая напарница — Оса.",
    "release_date": "2018-07-04"
  }, {
    "popularity": 287.807,
    "vote_count": 2019,
    "video": false,
    "poster_path": "/wh5FEKiNeirvD02T2Ui22duZGCZ.jpg",
    "id": 495764,
    "adult": false,
    "backdrop_path": "/pbOOOT0ASXjP4aJZr5NyOjK9qix.jpg",
    "original_language": "en",
    "original_title": "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
    "genre_ids": [28, 35, 80],
    "title": "Хищные птицы: Потрясающая история Харли Квинн",
    "vote_average": 7.1,
    "overview": "В центре сюжета окажется Харли Куинн, которая расстаётся со своим возлюбленным Джокером и собирает собственную команду опасных супергероинь. В их числе Бэтгёрл, Чёрная канарейка, Охотница и Рене Монтойя. Дерзким девушкам предстоит вступить в схватку с Чёрной Маской, который является криминальным авторитетом Готэма.",
    "release_date": "2020-02-05"
  }, {
    "popularity": 269.235,
    "vote_count": 4736,
    "video": false,
    "poster_path": "/2hDzCRhXWm5ry2nFs9HQBIon1DJ.jpg",
    "id": 353081,
    "adult": false,
    "backdrop_path": "/aw4FOsWr2FY373nKSxbpNi3fz4F.jpg",
    "original_language": "en",
    "original_title": "Mission: Impossible - Fallout",
    "genre_ids": [28, 12],
    "title": "Миссия невыполнима: Последствия",
    "vote_average": 7.3,
    "overview": "Итан Хант и его команда, а также недавно примкнувшие к ним союзники, вынуждены действовать наперегонки со временем, когда новая миссия идет не по плану.",
    "release_date": "2018-07-13"
  }, {
    "popularity": 219.402,
    "vote_count": 834,
    "video": false,
    "poster_path": "/AwsewPKXebJvtl4EU5Dx5uBCW6G.jpg",
    "id": 448119,
    "adult": false,
    "backdrop_path": "/xcUf6yIheo78btFqihlRLftdR3M.jpg",
    "original_language": "en",
    "original_title": "Dolittle",
    "genre_ids": [12, 35, 14, 10751],
    "title": "Удивительное путешествие доктора Дулиттла",
    "vote_average": 6.8,
    "overview": "Семь лет назад доктор Дулиттл, прославленный врач-ветеринар, живущий в викторианской Англии, потерял свою жену. Теперь он ведет затворнический образ жизни, скрывшись за высокими стенами своего поместья. Экзотические животные из его коллекции — его единственная компания. Но когда неизвестная болезнь становится угрозой для жизни юной королевы, доктору Дулиттлу приходится покинуть свое убежище и отправиться в невероятное путешествие к мифическому острову. В поисках лекарства для королевы он вступит в схватку с беспощадными врагами, познакомится с диковинными существами и будет вынужден проявить недюжинное мужество и смекалку.",
    "release_date": "2020-01-01"
  }, {
    "popularity": 217.705,
    "vote_count": 4,
    "video": false,
    "poster_path": "/j9vEMgw1Y7nG6gO1Zf516eAbVe5.jpg",
    "id": 587853,
    "adult": false,
    "backdrop_path": "/oKRxXFIND4GMNsjsTYdxKW67Mrk.jpg",
    "original_language": "id",
    "original_title": "Upin & Ipin: Keris Siamang Tunggal",
    "genre_ids": [],
    "title": "Upin & Ipin: Keris Siamang Tunggal",
    "vote_average": 7.1,
    "overview": "",
    "release_date": "2019-05-09"
  }, {
    "popularity": 212.719,
    "vote_count": 439,
    "video": false,
    "poster_path": "/xaJnPODeROjzvdiHotiF9YVdez2.jpg",
    "id": 508439,
    "adult": false,
    "backdrop_path": "/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg",
    "original_language": "en",
    "original_title": "Onward",
    "genre_ids": [12, 16, 35, 14, 10751],
    "title": "Вперёд",
    "vote_average": 7.9,
    "overview": "Из мира давно ушла вся магия. Теперь все волшебные существа, от эльфов до спрайтов, живут обычной жизнью и занимаются самыми обычными делами. Но двух братьев-эльфов не устраивает скучная жизнь в пригороде, и они отправляются в опасное путешествие, чтобы отыскать последние следы магии.",
    "release_date": "2020-02-29"
  }, {
    "popularity": 204.772,
    "vote_count": 2645,
    "video": false,
    "poster_path": "/mUuPQ7F7nw0ZJ7TlgQpKNVZnred.jpg",
    "id": 512200,
    "adult": false,
    "backdrop_path": "/hreiLoPysWG79TsyQgMzFKaOTF5.jpg",
    "original_language": "en",
    "original_title": "Jumanji: The Next Level",
    "genre_ids": [28, 12, 35, 14],
    "title": "Джуманджи: Новый уровень",
    "vote_average": 6.8,
    "overview": "Чтобы спасти одного из приятелей, остальным приходится вернуться в игру. К их удивлению, правила Джуманджи изменились, и все идет наперекосяк. Чтобы выжить друзьям предстоит отправиться в путешествие по самым неизведанным и таинственным уголкам игры — от засушливой пустыни до заснеженных гор.",
    "release_date": "2019-12-04"
  }, {
    "popularity": 189.175,
    "vote_count": 3545,
    "video": false,
    "poster_path": "/3O7jpvEEvBiR38P3GlcTwvv0EY3.jpg",
    "id": 181812,
    "adult": false,
    "backdrop_path": "/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg",
    "original_language": "en",
    "original_title": "Star Wars: The Rise of Skywalker",
    "genre_ids": [28, 12, 878],
    "title": "Звёздные войны: Скайуокер. Восход",
    "vote_average": 6.5,
    "overview": "Фильм завершает невероятную историю семьи Скайуокеров, длящуюся уже более сорока лет, и обещает дать ответы на все загадки из предыдущих серий. Зрителя ожидают старые и новые герои, уникальные миры, увлекательные путешествия на край Галактики и грандиозный финал фантастической саги.",
    "release_date": "2019-12-18"
  }, {
    "popularity": 174.779,
    "vote_count": 4,
    "video": false,
    "poster_path": "/g0c40ySJ1zW8dVwuCETgJcl3q7c.jpg",
    "id": 625985,
    "adult": false,
    "backdrop_path": "/j4B8G5yKRnTO655uvpQBXt4Ok08.jpg",
    "original_language": "ja",
    "original_title": "仮面ライダージオウNEXT TIME：ゲイツ、マジェスティ",
    "genre_ids": [28, 12, 878],
    "title": "仮面ライダージオウNEXT TIME：ゲイツ、マジェスティ",
    "vote_average": 7.8,
    "overview": "",
    "release_date": "2020-02-28"
  }, {
    "popularity": 168.23,
    "vote_count": 728,
    "video": false,
    "poster_path": "/wXWYJ7tKvUlryi6cCYYhk8ETuZV.jpg",
    "id": 475303,
    "adult": false,
    "backdrop_path": "/6fkqwqLEcDZOEAnBBfKAniwNxtx.jpg",
    "original_language": "en",
    "original_title": "A Rainy Day in New York",
    "genre_ids": [35, 10749],
    "title": "Дождливый день в Нью-Йорке",
    "vote_average": 6.6,
    "overview": "Он — из состоятельной семьи Нью-Йорка, она — из небольшого городка в Аризоне. Выросший на Манхэттене юноша мечтает показать ей свой любимый город. Судьба дает ему шанс, когда девушку отправляют взять интервью у известного режиссера. Однако этот дождливый день изменит их жизнь навсегда. В проливной суете мегаполиса он встретит свою давнюю подругу, а девушку затянет в мир звездной богемы…",
    "release_date": "2019-07-26"
  }, {
    "popularity": 160.402,
    "vote_count": 11957,
    "video": false,
    "poster_path": "/r7rLaG7ri160xobkDqS3S14YZ1s.jpg",
    "id": 245891,
    "adult": false,
    "backdrop_path": "/iJlGxN0p1suzloBGvvBu3QSSlhT.jpg",
    "original_language": "en",
    "original_title": "John Wick",
    "genre_ids": [28, 53],
    "title": "Джон Уик",
    "vote_average": 7.2,
    "overview": "Джон Уик — бывший наемный убийца — ведет размеренную жизнь, когда преступник крадет его любимый Mustang 1969 года и попутно убивает собаку Дейзи, единственное живое напоминание об умершей жене. Жажда мести пробуждает в нем, казалось, утерянную хватку.",
    "release_date": "2014-10-22"
  }, {
    "popularity": 158.595,
    "vote_count": 4871,
    "video": false,
    "poster_path": "/9NAGr8Z2OVURC4kjq31TIuNar4L.jpg",
    "id": 420818,
    "adult": false,
    "backdrop_path": "/nRXO2SnOA75OsWhNhXstHB8ZmI3.jpg",
    "original_language": "en",
    "original_title": "The Lion King",
    "genre_ids": [12, 10751],
    "title": "Король Лев",
    "vote_average": 7.1,
    "overview": "История об отважном львенке по имени Симба. Знакомые с детства герои взрослеют, влюбляются, познают себя и окружающий мир, совершают ошибки и делают правильный выбор.",
    "release_date": "2019-07-12"
  }, {
    "popularity": 152.12,
    "vote_count": 3297,
    "video": false,
    "poster_path": "/p4XurAYUUxsJgHEnGsPSqNMskYr.jpg",
    "id": 330457,
    "adult": false,
    "backdrop_path": "/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg",
    "original_language": "en",
    "original_title": "Frozen II",
    "genre_ids": [12, 16, 10751],
    "title": "Холодное сердце 2",
    "vote_average": 7.1,
    "overview": "Анна, Эльза, Кристоф, его верный олень Свен и никогда не унывающий снеговик Олаф должны будут покинуть уютное королевство Эренделл и отправиться ещё дальше на север, в путешествие, которое приведет их к истокам древних легенд и поможет раскрыть тайны, касающиеся прошлого их родной страны.",
    "release_date": "2019-11-20"
  }, {
    "popularity": 147.367,
    "vote_count": 873,
    "video": false,
    "poster_path": "/qv30R1uDDKTLWDlNc3qi6MRdRf0.jpg",
    "id": 619264,
    "adult": false,
    "backdrop_path": "/uNiTCaBIpw4vrRGEFKFm3VSt8Sm.jpg",
    "original_language": "es",
    "original_title": "El hoyo",
    "genre_ids": [18, 27, 878, 53],
    "title": "Платформа",
    "vote_average": 7.1,
    "overview": "В таинственной многоэтажной тюрьме платформа доставляет еду заключенным, но чем ниже они находятся, тем меньше шансов, что им достанется хоть что-то. Один из заключенных пытается изменить ситуацию.",
    "release_date": "2019-11-08"
  }, {
    "popularity": 145.432,
    "vote_count": 1605,
    "video": false,
    "poster_path": "/z7S7EX1YHOhCX9afC9aSyStJFEE.jpg",
    "id": 454626,
    "adult": false,
    "backdrop_path": "/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg",
    "original_language": "en",
    "original_title": "Sonic the Hedgehog",
    "genre_ids": [28, 35, 878, 10751],
    "title": "Соник в кино",
    "vote_average": 7.3,
    "overview": "Отвязный ярко-синий ежик Соник вместе с новообретенным — человеческим — лучшим другом Томом Вачовски он знакомится со сложностями жизни на Земле и противостоит злодейскому доктору Роботнику, который хочет пленить Соника и использовать его безграничные суперсилы для завоевания мирового господства.",
    "release_date": "2020-02-12"
  }, {
    "popularity": 143.992,
    "vote_count": 16,
    "video": false,
    "poster_path": "/iaTW57RK87v7ZrGkLKVofNH9YOr.jpg",
    "id": 505951,
    "adult": false,
    "backdrop_path": "/4zJbHJOshnAlQecHY5QjDvZQjeZ.jpg",
    "original_language": "ta",
    "original_title": "கண்ணும் கண்ணும் கொள்ளையடித்தால்",
    "genre_ids": [35, 18, 10749],
    "title": "கண்ணும் கண்ணும் கொள்ளையடித்தால்",
    "vote_average": 6.1,
    "overview": "Сиддарт по уши влюбляется в Миру, но все становится рискованно, когда они попадают в грязную ситуацию с опасным человеком.",
    "release_date": "2020-02-28"
  }, {
    "popularity": 141.622,
    "vote_count": 2946,
    "video": false,
    "poster_path": "/5CL4vOgjBoCBvGq3vklDKK3chT7.jpg",
    "id": 39538,
    "adult": false,
    "backdrop_path": "/57kqAPdVJTAJ4rnDTSVDx0f1JBu.jpg",
    "original_language": "en",
    "original_title": "Contagion",
    "genre_ids": [18, 878, 53],
    "title": "Заражение",
    "vote_average": 6.4,
    "overview": "Международная организация врачей совместно с Центром по контролю и профилактике заболеваний США пытается помешать распространению смертельного вируса.",
    "release_date": "2011-09-08"
  }
];
